// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res.status(200).json([
    {
      id: 1,
      created_at: "24/10/2021",
      nome: "Brunin",
      redes: "@inacio.lopes",
      intro:
        "Oi, sou surfista e professor de surf. Venha conhecer nosso projeto",
      endereco: "Rua poço da draga, 129",
      celular: "(85) 99999-9999",
      bio: "Vapo Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Vapo Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa.Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa.Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa.Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa.Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa.Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa.Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa.Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa.Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa.Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa.Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa.Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa. Lorem Ipsum is simply aaaaa.",
      qr_code: "",
      codigo_pix: "080.382.383-54",
      banco: "Banco do Brasil",
      agencia: "23154-5",
      conta: "23154-5",
    },
    {
      id: 2,
      created_at: "24/10/2021",
      nome: "Luiz Carlos",
      redes: "@inacio.lopes",
      intro:
        "Oi, sou surfista e professor de surf. Venha conhecer nosso projeto",
      endereco: "Rua poço da draga, 129",
      celular: "(85) 99999-9999",
      bio: "Lorem Ipsum is simply aaaaa.",
      qr_code: "",
      codigo_pix: "080.382.383-54",
      banco: "Banco do Brasil",
      agencia: "23154-5",
      conta: "23154-5",
    },
    {
      id: 3,
      created_at: "24/10/2021",
      nome: "Inácio Lopes",
      redes: "@inacio.lopes",
      intro:
        "Oi, sou surfista e professor de surf. Venha conhecer nosso projeto",
      endereco: "Rua poço da draga, 129",
      celular: "(85) 99999-9999",
      bio: "Lorem Ipsum is simply dummy text of the.",
      qr_code: "",
      codigo_pix: "080.382.383-54",
      banco: "Banco do Brasil",
      agencia: "23154-5",
      conta: "23154-5",
    },
    {
      id: 4,
      created_at: "24/10/2021",
      nome: "Inácio Lopes",
      redes: "@inacio.lopes",
      intro:
        "Oi, sou surfista e professor de surf. Venha conhecer nosso projeto",
      endereco: "Rua poço da draga, 129",
      celular: "(85) 99999-9999",
      bio: "Lorem Ipsum is simply dummy text of the.",
      qr_code: "",
      codigo_pix: "080.382.383-54",
      banco: "Banco do Brasil",
      agencia: "23154-5",
      conta: "23154-5",
    },
    {
      id: 5,
      created_at: "24/10/2021",
      nome: "Inácio Lopes",
      redes: "@inacio.lopes",
      intro:
        "Oi, sou surfista e professor de surf. Venha conhecer nosso projeto",
      endereco: "Rua poço da draga, 129",
      celular: "(85) 99999-9999",
      bio: "Lorem Ipsum is simply dummy text of the.",
      qr_code: "",
      codigo_pix: "080.382.383-54",
      banco: "Banco do Brasil",
      agencia: "23154-5",
      conta: "23154-5",
    },
    {
      id: 6,
      created_at: "24/10/2021",
      nome: "Inácio Lopes",
      redes: "@inacio.lopes",
      intro:
        "Oi, sou surfista e professor de surf. Venha conhecer nosso projeto",
      endereco: "Rua poço da draga, 129",
      celular: "(85) 99999-9999",
      bio: "Lorem Ipsum is simply dummy text of the.",
      qr_code: "",
      codigo_pix: "080.382.383-54",
      banco: "Banco do Brasil",
      agencia: "23154-5",
      conta: "23154-5",
    },
    {
      id: 7,
      created_at: "24/10/2021",
      nome: "Inácio Lopes",
      redes: "@inacio.lopes",
      intro:
        "Oi, sou surfista e professor de surf. Venha conhecer nosso projeto",
      endereco: "Rua poço da draga, 129",
      celular: "(85) 99999-9999",
      bio: "Lorem Ipsum is simply dummy text of the.",
      qr_code: "",
      codigo_pix: "080.382.383-54",
      banco: "Banco do Brasil",
      agencia: "23154-5",
      conta: "23154-5",
    },
    {
      id: 8,
      created_at: "24/10/2021",
      nome: "Inácio Lopes",
      redes: "@inacio.lopes",
      intro:
        "Oi, sou surfista e professor de surf. Venha conhecer nosso projeto",
      endereco: "Rua poço da draga, 129",
      celular: "(85) 99999-9999",
      bio: "Lorem Ipsum is simply dummy text of the.",
      qr_code: "",
      codigo_pix: "080.382.383-54",
      banco: "Banco do Brasil",
      agencia: "23154-5",
      conta: "23154-5",
    },
    {
      id: 9,
      created_at: "24/10/2021",
      nome: "Nivando",
      redes: "@inacio.lopes",
      intro:
        "Oi, sou surfista e professor de surf. Venha conhecer nosso projeto",
      endereco: "Rua poço da draga, 129",
      celular: "(85) 99999-9999",
      bio: "Lorem Ipsum is simply dummy text of the.",
      qr_code: "",
      codigo_pix: "111.111.111-35",
      banco: "Banco do Brasil",
      agencia: "23154-5",
      conta: "23154-5",
    },
  ]);
}
